name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync --dev
      - name: Lint
        run: uv run ruff check
      - name: Type check
        run: uv run mypy src
      - name: Test
        run: uv run pytest
